// @vitest-environment node

import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'
import { resolve } from 'node:path'

import { buildBlankDocx } from '@jobos/docx-engine'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'

import { DocxExternalChangeError, DocxFileStore, sha256 } from './docxFileStore.js'

let root: string
let store: DocxFileStore
let source: Uint8Array
let target: string

beforeEach(async () => {
  root = await mkdtemp(path.join(os.tmpdir(), 'jobos-docx-store-'))
  store = new DocxFileStore({ recoveryRoot: path.join(root, 'recovery'), keepRecoveries: 3 })
  source = new Uint8Array(await readFile(resolve(process.cwd(), '../../packages/docx-engine/tests/fixtures/(FAKE)-polished-resume.docx')))
  target = path.join(root, '(FAKE)-resume.docx')
  await writeFile(target, source)
})

afterEach(async () => { await rm(root, { recursive: true, force: true }) })

describe('DocxFileStore', () => {
  it('validates generated bytes before touching the canonical file', async () => {
    await expect(store.replace('docx_000000000000000000000000', target, sha256(source), new Uint8Array([1, 2, 3])))
      .rejects.toThrow('invalid')
    expect(new Uint8Array(await readFile(target))).toEqual(source)
  })

  it('creates a recovery and atomically replaces the expected revision', async () => {
    const replacement = await buildBlankDocx()
    const result = await store.replace('docx_000000000000000000000000', target, sha256(source), replacement, 'manual')
    expect((await store.read(target)).sha256).toBe(sha256(replacement))
    expect(result.recovery.reason).toBe('manual')
    expect(await store.recoveryBytes(result.recovery.bindingId, result.recovery.recoveryId)).toEqual(source)
  })

  it('refuses to overwrite an externally changed revision', async () => {
    const external = await buildBlankDocx()
    await writeFile(target, external)
    await expect(store.replace('docx_000000000000000000000000', target, sha256(source), source))
      .rejects.toBeInstanceOf(DocxExternalChangeError)
    expect(new Uint8Array(await readFile(target))).toEqual(external)
  })

  it('preserves an external save that lands immediately before the atomic exchange', async () => {
    const external = await buildBlankDocx()
    const guarded = new DocxFileStore({
      recoveryRoot: path.join(root, 'race-recovery'),
      beforeAtomicReplace: async () => { await writeFile(target, external) }
    })

    await expect(guarded.replace(
      'docx_000000000000000000000000',
      target,
      sha256(source),
      source
    )).rejects.toBeInstanceOf(DocxExternalChangeError)
    expect(new Uint8Array(await readFile(target))).toEqual(external)
  })

  it('serializes concurrent writes so only the first expected revision wins', async () => {
    const replacement = await buildBlankDocx()
    const expected = sha256(source)
    const [first, second] = await Promise.allSettled([
      store.replace('docx_000000000000000000000000', target, expected, replacement),
      store.replace('docx_000000000000000000000000', target, expected, source)
    ])
    expect([first.status, second.status].sort()).toEqual(['fulfilled', 'rejected'])
  })

  it('does not clobber a file that already exists when creating a new DOCX', async () => {
    const replacement = await buildBlankDocx()
    await expect(store.writeNew(target, replacement)).rejects.toMatchObject({ code: 'EEXIST' })
    expect(new Uint8Array(await readFile(target))).toEqual(source)
  })

  it('rejects configured immutable artifact roots', () => {
    const guarded = new DocxFileStore({ recoveryRoot: path.join(root, 'recovery'), denyRoots: [path.join(root, 'artifacts')] })
    expect(() => guarded.assertWritablePath(path.join(root, 'artifacts', 'hash.docx'))).toThrow('immutable')
    expect(() => guarded.assertWritablePath(target)).not.toThrow()
  })
})
